Update run_PowerShell.yml

diff --git a/.github/workflows/run_PowerShell.yml b/.github/workflows/run_PowerShell.yml
--- a/.github/workflows/run_PowerShell.yml
+++ b/.github/workflows/run_PowerShell.yml
@@ -13,6 +13,12 @@ jobs:
     - name: Checkout repository
       uses: actions/checkout@v3
 
+    - name: Install latest Azure CLI
+      run: |
+        Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi
+        Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'
+        az version
+
     - name: Run PowerShell script
       shell: pwsh
       run: |
@@ -35,7 +41,7 @@ jobs:
           ./script_output.ps1
         
         }
-          catch {
-            Write-Error "Script execution failed: $_"
-            exit 1
+        catch {
+          Write-Error "Script execution failed: $_"
+          exit 1
         }
